<?xml version="1.0" encoding="utf-8"?><Database Name="WorldMap" Class="DBEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=WorldMap;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.localizations" Member="localizations">
    <Type Name="localization">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[key]" Member="key" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="en" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ru" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.pageCategories" Member="pageCategories">
    <Type Name="pageCategory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_ru" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="name_en" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Association Name="pageCategory_page" Member="pages" ThisKey="ID" OtherKey="pagCategory_ID" Type="page" />
    </Type>
  </Table>
  <Table Name="dbo.pages" Member="pages">
    <Type Name="page">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pagCategory_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="header_ru" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="html_ru" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="isTop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="header_en" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="html_en" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="pageCategory_page" Member="pageCategory" ThisKey="pagCategory_ID" OtherKey="ID" Type="pageCategory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>