#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WorldMap")]
	public partial class DBEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlocalization(localization instance);
    partial void Updatelocalization(localization instance);
    partial void Deletelocalization(localization instance);
    partial void InsertpageCategory(pageCategory instance);
    partial void UpdatepageCategory(pageCategory instance);
    partial void DeletepageCategory(pageCategory instance);
    partial void Insertpage(page instance);
    partial void Updatepage(page instance);
    partial void Deletepage(page instance);
    #endregion
		
		public DBEntityDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<localization> localizations
		{
			get
			{
				return this.GetTable<localization>();
			}
		}
		
		public System.Data.Linq.Table<pageCategory> pageCategories
		{
			get
			{
				return this.GetTable<pageCategory>();
			}
		}
		
		public System.Data.Linq.Table<page> pages
		{
			get
			{
				return this.GetTable<page>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.localizations")]
	public partial class localization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _key;
		
		private string _en;
		
		private string _ru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnkeyChanging(string value);
    partial void OnkeyChanged();
    partial void OnenChanging(string value);
    partial void OnenChanged();
    partial void OnruChanging(string value);
    partial void OnruChanged();
    #endregion
		
		public localization()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[key]", Storage="_key", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string key
		{
			get
			{
				return this._key;
			}
			set
			{
				if ((this._key != value))
				{
					this.OnkeyChanging(value);
					this.SendPropertyChanging();
					this._key = value;
					this.SendPropertyChanged("key");
					this.OnkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string en
		{
			get
			{
				return this._en;
			}
			set
			{
				if ((this._en != value))
				{
					this.OnenChanging(value);
					this.SendPropertyChanging();
					this._en = value;
					this.SendPropertyChanged("en");
					this.OnenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ru", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ru
		{
			get
			{
				return this._ru;
			}
			set
			{
				if ((this._ru != value))
				{
					this.OnruChanging(value);
					this.SendPropertyChanging();
					this._ru = value;
					this.SendPropertyChanged("ru");
					this.OnruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pageCategories")]
	public partial class pageCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name_ru;
		
		private string _name_en;
		
		private EntitySet<page> _pages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onname_ruChanging(string value);
    partial void Onname_ruChanged();
    partial void Onname_enChanging(string value);
    partial void Onname_enChanged();
    #endregion
		
		public pageCategory()
		{
			this._pages = new EntitySet<page>(new Action<page>(this.attach_pages), new Action<page>(this.detach_pages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_ru", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string name_ru
		{
			get
			{
				return this._name_ru;
			}
			set
			{
				if ((this._name_ru != value))
				{
					this.Onname_ruChanging(value);
					this.SendPropertyChanging();
					this._name_ru = value;
					this.SendPropertyChanged("name_ru");
					this.Onname_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_en", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string name_en
		{
			get
			{
				return this._name_en;
			}
			set
			{
				if ((this._name_en != value))
				{
					this.Onname_enChanging(value);
					this.SendPropertyChanging();
					this._name_en = value;
					this.SendPropertyChanged("name_en");
					this.Onname_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pageCategory_page", Storage="_pages", ThisKey="ID", OtherKey="pagCategory_ID")]
		public EntitySet<page> pages
		{
			get
			{
				return this._pages;
			}
			set
			{
				this._pages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pages(page entity)
		{
			this.SendPropertyChanging();
			entity.pageCategory = this;
		}
		
		private void detach_pages(page entity)
		{
			this.SendPropertyChanging();
			entity.pageCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pages")]
	public partial class page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _pagCategory_ID;
		
		private string _header_ru;
		
		private string _html_ru;
		
		private System.DateTime _created;
		
		private string _image;
		
		private bool _isTop;
		
		private string _header_en;
		
		private string _html_en;
		
		private EntityRef<pageCategory> _pageCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnpagCategory_IDChanging(int value);
    partial void OnpagCategory_IDChanged();
    partial void Onheader_ruChanging(string value);
    partial void Onheader_ruChanged();
    partial void Onhtml_ruChanging(string value);
    partial void Onhtml_ruChanged();
    partial void OncreatedChanging(System.DateTime value);
    partial void OncreatedChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnisTopChanging(bool value);
    partial void OnisTopChanged();
    partial void Onheader_enChanging(string value);
    partial void Onheader_enChanged();
    partial void Onhtml_enChanging(string value);
    partial void Onhtml_enChanged();
    #endregion
		
		public page()
		{
			this._pageCategory = default(EntityRef<pageCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagCategory_ID", DbType="Int NOT NULL")]
		public int pagCategory_ID
		{
			get
			{
				return this._pagCategory_ID;
			}
			set
			{
				if ((this._pagCategory_ID != value))
				{
					if (this._pageCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpagCategory_IDChanging(value);
					this.SendPropertyChanging();
					this._pagCategory_ID = value;
					this.SendPropertyChanged("pagCategory_ID");
					this.OnpagCategory_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header_ru", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string header_ru
		{
			get
			{
				return this._header_ru;
			}
			set
			{
				if ((this._header_ru != value))
				{
					this.Onheader_ruChanging(value);
					this.SendPropertyChanging();
					this._header_ru = value;
					this.SendPropertyChanged("header_ru");
					this.Onheader_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_ru", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string html_ru
		{
			get
			{
				return this._html_ru;
			}
			set
			{
				if ((this._html_ru != value))
				{
					this.Onhtml_ruChanging(value);
					this.SendPropertyChanging();
					this._html_ru = value;
					this.SendPropertyChanged("html_ru");
					this.Onhtml_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime NOT NULL")]
		public System.DateTime created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(400)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isTop", DbType="Bit NOT NULL")]
		public bool isTop
		{
			get
			{
				return this._isTop;
			}
			set
			{
				if ((this._isTop != value))
				{
					this.OnisTopChanging(value);
					this.SendPropertyChanging();
					this._isTop = value;
					this.SendPropertyChanged("isTop");
					this.OnisTopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header_en", DbType="NVarChar(400)")]
		public string header_en
		{
			get
			{
				return this._header_en;
			}
			set
			{
				if ((this._header_en != value))
				{
					this.Onheader_enChanging(value);
					this.SendPropertyChanging();
					this._header_en = value;
					this.SendPropertyChanged("header_en");
					this.Onheader_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_en", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string html_en
		{
			get
			{
				return this._html_en;
			}
			set
			{
				if ((this._html_en != value))
				{
					this.Onhtml_enChanging(value);
					this.SendPropertyChanging();
					this._html_en = value;
					this.SendPropertyChanged("html_en");
					this.Onhtml_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pageCategory_page", Storage="_pageCategory", ThisKey="pagCategory_ID", OtherKey="ID", IsForeignKey=true)]
		public pageCategory pageCategory
		{
			get
			{
				return this._pageCategory.Entity;
			}
			set
			{
				pageCategory previousValue = this._pageCategory.Entity;
				if (((previousValue != value) 
							|| (this._pageCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pageCategory.Entity = null;
						previousValue.pages.Remove(this);
					}
					this._pageCategory.Entity = value;
					if ((value != null))
					{
						value.pages.Add(this);
						this._pagCategory_ID = value.ID;
					}
					else
					{
						this._pagCategory_ID = default(int);
					}
					this.SendPropertyChanged("pageCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
